# Datos de conexión Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/TFG
spring.datasource.username=postgres
spring.datasource.password=Atletico_10

spring.jpa.show-sql=true

# Habilita Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
# Ruta de la aplicación (si aplica)
springdoc.swagger-ui.path=/swagger-ui.html
# 1. Indicar que queremos inicializar la base de datos
spring.sql.init.mode=always

# 2. Ruta de tus archivos (asumiendo que están en src/main/resources/BBDD)
spring.sql.init.schema-locations=classpath:creacionBBDD.sql
spring.sql.init.data-locations=classpath:insertarDatos.sql

# 3. Para evitar errores si las tablas ya existen (si tu script no tiene "IF NOT EXISTS")
spring.sql.init.continue-on-error=true

# 4. Configurar Hibernate para que no intente crear las tablas por su cuenta
# Queremos que lo haga nuestro script SQL
spring.jpa.hibernate.ddl-auto=none